const marvelImages = {
  name: 'marvel',
  img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/marvel.png',
  children: [
    {
      name: 'Heroes',
      children: [
        {
          hero: 'Spider Man',
          elName: 'spiderMan',
          name: 'Peter Benjamin Parker',
          link: 'http://marvel.com/characters/54/spider-man',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_spiderman.png',
          size: 40000,
        },
        {
          hero: 'CAPTAIN MARVEL',
          elName: 'captainMarvel',
          name: 'Carol Danvers',
          link: 'http://marvel.com/characters/9/captain_marvel',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_captainmarvel.png',
          size: 40000,
        },
        {
          hero: 'HULK',
          elName: 'hulk',
          name: 'Robert Bruce Banner',
          link: 'http://marvel.com/characters/25/hulk',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_hulk.png',
          size: 40000,
        },
        {
          hero: 'Black Widow',
          elName: 'blackWidow',
          name: 'Natalia \'Natasha\' Alianovna Romanova',
          link: 'http://marvel.com/characters/6/black_widow',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_blackwidow.png',
          size: 40000,
        },
        {
          hero: 'Daredevil',
          elName: 'dareDevil',
          name: 'Matthew Michael Murdock',
          link: 'http://marvel.com/characters/11/daredevil',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_daredevil.png',
          size: 40000,
        },
        {
          hero: 'Wolverine',
          elName: 'wolverine',
          name: 'James Howlett',
          link: 'http://marvel.com/characters/66/wolverine',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_wolverine.png',
          size: 40000,
        },
        {
          hero: 'Captain America',
          elName: 'captainAmerica',
          name: 'Steven Rogers',
          link: 'http://marvel.com/characters/8/captain_america',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_captainamerica.png',
          size: 40000,
        },
        {
          hero: 'Iron Man',
          elName: 'ironMan',
          name: 'Anthony Edward \'Tony\' Stark',
          link: 'http://marvel.com/characters/29/iron_man',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_ironman.png',
          size: 40000,
        },
        {
          hero: 'THOR',
          elName: 'thor',
          name: 'Thor Odinson',
          link: 'http://marvel.com/characters/60/thor',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/top_thor.png',
          size: 40000,
        },
      ],
    },
    {
      name: 'Villains',
      children: [
        {
          hero: 'Dr Doom',
          elName: 'drDoom',
          name: 'Victor von Doom',
          link: 'http://marvel.com/characters/13/dr_doom',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/drdoom.png',
          size: 40000,
        },
        {
          hero: 'Mystique',
          elName: 'mystique',
          name: 'Unrevealed',
          link: 'http://marvel.com/characters/1552/mystique',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/mystique.png',
          size: 40000,
        },
        {
          hero: 'Red Skull',
          elName: 'redSkull',
          name: 'Johann Shmidt',
          link: 'http://marvel.com/characters/1901/red_skull',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/redskull.png',
          size: 40000,
        },
        {
          hero: 'Ronan',
          elName: 'ronan',
          name: 'Ronan',
          link: 'http://marvel.com/characters/49/ronan',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/ronan.png',
          size: 40000,
        },
        {
          hero: 'Magneto',
          elName: 'magneto',
          name: 'Max Eisenhardt',
          link: 'http://marvel.com/characters/35/magneto',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/magneto.png',
          size: 40000,
        },
        {
          hero: 'Thanos',
          elName: 'thanos',
          name: 'Thanos',
          link: 'http://marvel.com/characters/58/thanos',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/thanos.png',
          size: 40000,
        },
        {
          hero: 'Black Cat',
          elName: 'blackCat',
          name: 'Felicia Hardy',
          link: 'http://marvel.com/characters/271/black_cat',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/blackcat.png',
          size: 40000,
        },
      ],
    },
    {
      name: 'Teams',
      children: [
        {
          hero: 'Avengers',
          elName: 'avengers',
          name: '',
          link: 'http://marvel.com/characters/68/avengers',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/avengers.png',
          size: 40000,
        },
        {
          hero: 'Guardians of the Galaxy',
          elName: 'guardiansOfTheGalaxy',
          name: '',
          link: 'http://marvel.com/characters/70/guardians_of_the_galaxy',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/gofgalaxy.png',
          size: 40000,
        },
        {
          hero: 'Defenders',
          elName: 'defenders',
          name: '',
          link: 'http://marvel.com/characters/534/defenders',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/defenders.png',
          size: 40000,
        },
        {
          hero: 'X Men',
          elName: 'xMen',
          name: '',
          link: 'http://marvel.com/characters/71/x-men',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/xmen.png',
          size: 40000,
        },
        {
          hero: 'Fantastic Four',
          elName: 'fantasticFour',
          name: '',
          link: 'http://marvel.com/characters/69/fantastic_four',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/fantasticfour.png',
          size: 40000,
        },
        {
          hero: 'Inhumans',
          elName: 'inHumans',
          name: '',
          link: 'http://marvel.com/characters/1040/inhumans',
          img: 'http://marvel-force-chart.surge.sh/marvel_force_chart_img/inhumans.png',
          size: 40000,
        },
      ],
    },
  ],
};

export default marvelImages;
